# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"
    filter_sets:
        grand_slider_homepage:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [800, 605], mode: outbound }        
        medium_slider_homepage:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [800, 300], mode: outbound }        
        small_slider_homepage:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [400, 300], mode: outbound }